name: deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --force --ignore-scripts

      - name: Download .env.production file and delete it after the workflow is finished
        uses: zdeneklapes/dotenv-vault-action@v2
        with:
          dotenvMe: ${{ secrets.DOTENV_ME }}
          stage: 'production'
          delete: 'true'

      - name: Generate Prisma
        run: npx prisma generate
      - name: Build
        run: npm run build

      - name: Compress Files
        run: zip --symlinks -r my-api.zip .

      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade --user
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Initialize Elastic Beanstalk
        run: echo "n" | eb init my-api --region ${{secrets.AWS_REGION}}

      - name: Deploy to Elastic BeanStalk
        run: eb deploy test --staged --label test-my-api-${{ github.run_id }}-${{github.event.repository.pushed_at}}
